name: Security Monitoring

on:
  schedule:
    # Run security checks daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  security-audit:
    name: Comprehensive Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://iron-shop-nextjs.vercel.app'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          command: test

      - name: Run Semgrep Security Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/owasp-top-ten

      - name: Create Security Report Issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Security Vulnerability Detected - ' + new Date().toISOString().split('T')[0],
              body: '🚨 Security scan detected potential vulnerabilities. Please review the workflow logs for details.\n\n**Scan Date:** ' + new Date().toISOString() + '\n**Workflow:** ${{ github.workflow }}\n**Run ID:** ${{ github.run_id }}',
              labels: ['security', 'bug', 'high-priority']
            })

  dependency-monitor:
    name: Dependency Monitoring
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iron-shop-nextjs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './iron-shop-nextjs/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Check for vulnerable dependencies
        run: |
          npm audit --audit-level=high --json > audit-report.json || true
          
      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-audit-report
          path: ./iron-shop-nextjs/audit-report.json
          retention-days: 30

      - name: Check dependency licenses
        run: |
          npx license-checker --onlyAllow 'MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC' --summary || true